<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
genesis_markup(
	[
		'close'   => '</div>',
		'context' => 'site-inner',
	]
);

/**
 * Fires immediately after the site inner closing markup, before `genesis_footer` action hook.
 *
 * @since 1.0.0
 */
do_action( 'genesis_before_footer' );

/**
 * Fires to display the main footer content.
 *
 * @since 1.0.1
 */
do_action( 'genesis_footer' );

/**
 * Fires immediately after the `genesis_footer` action hook, before the site container closing markup.
 *
 * @since 1.0.0
 */
do_action( 'genesis_after_footer' );

genesis_markup(
	[
		'close'   => '</div>',
		'context' => 'site-container',
	]
);

/**
 * Fires immediately before wp_footer(), after the site container closing markup.
 *
 * @since 1.0.0
 */
do_action( 'genesis_after' );
wp_footer(); // We need this for plugins.

genesis_markup(
	[
		'close'   => '</body>',
		'context' => 'body',
	]
);

?>


<!-- custom footer -->
<footer id="custom-footer">

<div class="home-footer">
 
<div class=" container">
	<div class="row">
		<div class="col-md-4 col-lg-4 col-sm-12">
          <?php if ( is_active_sidebar( 'home-footer_one' ) ) { ?>
                  <div class="sidebar-column"><!-- sidebar-column -->
				<?php dynamic_sidebar( 'home-footer_one' ); ?>
                 </div><!-- sidebar-column -->
		      <?php } ?>

			

		</div>
		<div class="col-md-2 col-lg-2 col-sm-12">
              <div class="footer-menu">
               <?php if ( is_active_sidebar( 'home-footer_two' ) ) { ?>
                  <div class="sidebar-column"><!-- sidebar-column -->
				<?php dynamic_sidebar( 'home-footer_two' ); ?>
                 </div><!-- sidebar-column -->
		      <?php } ?>

			
			 
			  	
			  </div>
		</div>
		<div class="col-md-2 col-lg-2 col-sm-12">
			<div class="footer-menu">
				<?php if ( is_active_sidebar( 'home-footer_three' ) ) { ?>
                  <div class="sidebar-column"><!-- sidebar-column -->
				<?php dynamic_sidebar( 'home-footer_three' ); ?>
                 </div><!-- sidebar-column -->
		      <?php } ?>
			
			  
			 
			  </div>
		</div>
		<div class="col-md-2 col-lg-2 col-sm-12">
			<div class="footer-menu"> 
				<?php if ( is_active_sidebar( 'home-footer_four' ) ) { ?>
                  <div class="sidebar-column"><!-- sidebar-column -->
				<?php dynamic_sidebar( 'home-footer_four' ); ?>
                 </div><!-- sidebar-column -->
		      <?php } ?>
			 
			  
			  </div>
		</div>
		<div class="col-md-2 col-lg-2 col-sm-12">
		 <div class="footer-menu">	
		 	<?php if ( is_active_sidebar( 'home-footer_five' ) ) { ?>
                  <div class="sidebar-column"><!-- sidebar-column -->
				<?php dynamic_sidebar( 'home-footer_five' ); ?>
                 </div><!-- sidebar-column -->
		      <?php } ?>
			  
			 
			  
			  </div>
		</div>

	</div>


<div class="row">
		<div class="col-md-4 col-lg-4 col-sm-12">
			<div class=""> 
              

            


			 </div>

		</div>
		<div class="col-md-3 col-lg-3 col-sm-12">
			<div class="footer-logo"> 
              <img src="/wp-content/uploads/2020/07/amazon.png">
              <img src="/wp-content/uploads/2020/07/amex-label.png">
              <img src="/wp-content/uploads/2020/07/omni.png">
              <img src="/wp-content/uploads/2020/07/p-label.png">
              <img src="/wp-content/uploads/2020/07/visa.png">
			 </div>

		</div>
		
		<div class="col-md-3 col-lg-3 col-sm-12">
			<div class="footer-text-icon"> 
              <img src="/wp-content/uploads/2020/07/vit.png">
              
			</div>
			
		</div>

		<div class="col-md-2 col-lg-2 col-sm-12">
			<div class="footer-text"> 
               <p class="footer-last"> © 2020 Nutrachamps</p>
			</div>
		</div>

	</div>

</div>

<hr style="background-color: #8e8a8a;">
<div class="container-fluid px-4 " style=" text-align: center;     font-size: 13px;">
	These statements have not been evaluated by the Food and Drug Administration. This product is not intended to diagnose, treat, cure, or prevent any disease. As with any dietary supplement, you should advise your healthcare practitioner of the use of this product
</div>	
	</div>
</footer>


<!-- blogs pages footers -->

<footer id="posts-pages-footer">
	<div class="let-be-friend">
		<div class="container">
			<ul>
				<li>LET'S BE FRIENDS</li>
				<li>
				  <img src="https://acid-spider.wp.work/wp-content/uploads/2020/06/facebook-footer.png">
                  <h2>4.8M</h2>
                  <p>Likes</p>
				</li>

				<li>
					<img src="https://acid-spider.wp.work/wp-content/uploads/2020/06/insta.png">
                  <h2>532K</h2>
                  <p>Followers</p>	
				</li>

				<li>
				  <img src="https://acid-spider.wp.work/wp-content/uploads/2020/06/youtube.png">
                  <h2>1.7M</h2>
                  <p>Subscribers</p>
				</li>

				<li>
				  <img src="https://acid-spider.wp.work/wp-content/uploads/2020/06/pinerest.png">
                  <h2>474K</h2>
                  <p>Followers</p>
				</li>
			</ul>
			
		</div>
	</div>

<!-- second line footer -->
<div class="post-2-f">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-sm-12 col-lg-4 footer-logo-sec">
				
				<?php if ( is_active_sidebar( 'footer_one' ) ) { ?>
                  <div class="sidebar-column"><!-- sidebar-column -->
				<?php dynamic_sidebar( 'footer_one' ); ?>
                 </div><!-- sidebar-column -->
		      <?php } ?>
			</div>

			<div class="col-lg-2 col-lg-2 col-sm-12 "  class="nav-menu">
				<h2>Navigation</h2>
				<?php if ( is_active_sidebar( 'footer_two' ) ) { ?>
                  <div class="sidebar-column"><!-- sidebar-column -->
				<?php dynamic_sidebar( 'footer_two' ); ?>
                 </div><!-- sidebar-column -->
		      <?php } ?>
				
			</div>
			
			<div class="col-lg-2 col-lg-2 col-sm-12" class="nav-menu">

               <h2>Navigation</h2>
				
				<?php if ( is_active_sidebar( 'footer_three' ) ) { ?>
                  <div class="sidebar-column"><!-- sidebar-column -->
				<?php dynamic_sidebar( 'footer_three' ); ?>
                 </div><!-- sidebar-column -->
		      <?php } ?>
			</div>

			<div class="col-md-4 col-sm-12 col-lg-4"  class="footer-form">
			
				<?php if ( is_active_sidebar( 'footer_four' ) ) { ?>
                  <div class="sidebar-column"><!-- sidebar-column -->
				<?php dynamic_sidebar( 'footer_four' ); ?>
                 </div><!-- sidebar-column -->
		      <?php } ?>
			</div>
		</div>
		
	
	
<hr>
       <h2 class="text-center py-3">Medical Disclaimer</h2>
        <p class="text-center pb-4">
        	This content is for informational and educational purposes only. It is not intended to provide medical advice or to take the place of such advice or treatment from a personal physician. All readers/viewers of this content are advised to consult their doctors or qualified health professionals regarding specific health questions. Neither Dr. Axe nor the publisher of this content takes responsibility for possible health consequences of any person or persons reading or following the information in this educational content. All viewers of this content, especially those taking prescription or over-the-counter medications, should consult their physicians before beginning any nutrition, supplement or lifestyle program. 
        </p>
        <hr>

        <h3 class="text-center py-5">© <?php echo date('Y'); ?> NutraChamps. All Rights Reserved.  |  Privacy Policy   |  Terms of Use   </h3>
</div>
</div>
</footer>



</html>
